version: '3'

services:
  astro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:4321"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development

